### ISSUE TITLE
f9edfc16bc5d7e3f795025ac6fa3d6608634e18a breaks builds in a tmpdir

### ISSUE THREAD

**Issue by dunn** [editorconfig/editorconfig-emacs#105]
As of https://github.com/editorconfig/editorconfig-emacs/commit/f9edfc16bc5d7e3f795025ac6fa3d6608634e18a, the following doesn't work:
```
git clone https://github.com/editorconfig/editorconfig-emacs.git
mv editorconfig-emacs /tmp/
cd /tmp/editorconfig-emacs
make test
```
This isn't a totally bizarre use-case; Homebrew and perhaps other package managers cache a download, then copy the source tree to a temporary directory during the install step.

**Comment by dunn** [comment]
Forgot to post the make output: https://gist.github.com/dunn/29f7fd0cc3b8f07cdb1f3b0f5e25a1a1

**Comment by 10sr** [comment]
Sorry for inconvenience 🙇 
I've pushed a revert commit for that and bumped version to v0.7.8 .

**Comment by dunn** [comment]
Oh, thanks!

Out of curiousity, what was that change supposed to do?

**Comment by 10sr** [comment]
The `conf` value will be used as a key to get and set a cache for a parsed result of an `.editorconfig` file.
By passing it to `file-truename`, I expected that caches can be reused for some cases: For example, when `/foo/.editorconfig` is a symlink file to `/foo/bar/.editorconfig`, it would be nice if we can use the same cached data for `/foo/bar/.editorconfig` and `/foo/.editorconfig`!
We can expect that it would save some time and work to access files and parse data in such a case.

And, yes, I think it is not likely to bring a big performance improvements, so no problem without this feature XD.
(I think the problem is related to  `fnmatch` calls in cases like this, but did not look into it deeply :) )
