### ISSUE TITLE
Silence emacs compile warnings

### ISSUE THREAD

**Issue by paddy-hack** [editorconfig/editorconfig-emacs#127]
Just pulled and compiled 0.7.9 via `use-package` and found the following in the compile output:
```
Compiling file /home/paddy-hack/.emacs.d/elpa/editorconfig-0.7.9/editorconfig.el at Mon Apr 17 18:48:20 2017

In editorconfig-set-indentation/latex-mode:
editorconfig.el:259:48:Warning: assignment to free variable `tex-indent-basic'
editorconfig.el:260:47:Warning: assignment to free variable `tex-indent-item'
editorconfig.el:261:51:Warning: assignment to free variable `tex-indent-arg'

In editorconfig-set-indentation:
editorconfig.el:300:74:Warning: assignment to free variable `evil-shift-width'
```
I'm a bit allergic to warnings :wink: so figured you might want to clean this up.

**Comment by xuhdev** [comment]
This can be fixed in two ways but both have their downsides.

- We add `;; byte-compile-warnings: (not free-vars)` to [suppress all free variable warnings](https://emacs.stackexchange.com/a/19507/2755). This obviously will dismiss relevant free variable warnings.

- We add `(require xxx)` for each free variable. This will significantly increase the loading time.

@10sr What do you think?

**Comment by 10sr** [comment]
Thanks! 👍 

There is a clear solution for this problem, adding `(defvar VAR)` for each variable.
I could not find the official document, but as I remember this is the offcial way to get rid of such messages.

http://stackoverflow.com/questions/12432093/get-rid-of-reference-to-free-variable-byte-compilation-warnings#12434028
https://www.emacswiki.org/emacs/FreeVariable
