### ISSUE TITLE
Doesn't work automatically in OrcSrc buffer

### ISSUE THREAD

**Issue by amosbird** [editorconfig/editorconfig-emacs#142]
When doing `org-edit-special`, editorconfig-mode doesn't set the indentation correctly. I have to manually do `editorconfig-apply`

**Comment by 10sr** [comment]
Sorry for taking very very long time to look into this.

Unfortunately, it is difficult to natively support `org-edit-special` in editorconfig-mode because of org-edit-special's tricky initialization (buffer-file-name is set  to nil when editorconfig hook is called).
Alternatively, you can add following lines to your init.el, when you are going to edit source code with `org-edit-special`:

```el
(with-eval-after-load 'org-src
    (add-hook 'org-src-mode-hook
              'editorconfig-mode-apply t))
```

**Comment by 10sr** [comment]
Closing because there are no update recently.
Please feel free to reopen issue if the problem still exists.
